version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@postgres_db:5432/currency?sslmode=disable",
      "up"
    ]
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  app:
    build: .
    container_name: rnd_service
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - CONFIG_PATH=/root/config/config.yaml

volumes:
  postgres_data: