app:
  name: "RnD-service"
  port: "8080"

log:
  level: "debug"

postgres:
  host: "db"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "currency"
  sslmode: "disable"
